export default {
    GET_HISTORY_HORSENS: "GET_HISTORY_HORSENS",
    GET_HISTORY_AARHUS: "GET_HISTORY_AARHUS",
    GET_HISTORY_CONPENHAGEN: "GET_HISTORY_CONPENHAGEN",
    GET_FORECAST_HORSENS: "GET_FORECAST_HORSENS",
    GET_FORECAST_AARHUS: "GET_FORECAST_AARHUS",
    GET_FORECAST_CONPENHAGEN: "GET_FORECAST_CONPENHAGEN",
//Amahdya
    GET_FORECAST_DATES: "GET_FORECAST_DATES",
    POST_HISTORY: "POST_HISTORY",
};
