export default {
    GET_HISTORY_HORSENS: "GET_HISTORY_HORSENS",
    GET_HISTORY_AARHUS: "GET_HISTORY_AARHUS",
    GET_HISTORY_CONPENHAGEN: "GET_HISTORY_CONPENHAGEN",
    GET_FORECAST_HORSENS: "GET_FORECAST_HORSENS",
    GET_FORECAST_AARHUS: "GET_FORECAST_AARHUS",
    GET_FORECAST_CONPENHAGEN: "GET_FORECAST_CONPENHAGEN",
};
